// ═══════════════════════════════════════════════════════
// TOPIC MODULE: Load Balancers
// To add a new topic: copy this file, change TOPIC_META
// and replace ICONS, SVC, TREE data. Register in app.js.
// ═══════════════════════════════════════════════════════

window.TOPIC_LB = (function() {

const META = {
  id: 'lb',
  label: 'Load Balancers',
  icon: '⚖️',
  desc: 'Route traffic across compute backends — Layer 4, Layer 7, global anycast, CDN',
  clouds: ['azure','aws','gcp'],
  views: ['tree','gallery','compare'],
  heroTitle: 'Which Load Balancer suits your workload?',
  heroSub: 'Answer questions · Get the right service · See animated diagrams',
  chips: {
    azure: ['⚖️ Load Balancer','🛡️ App Gateway','🚀 Front Door','🌐 Traffic Manager','🔌 API Management'],
    aws:   ['🔀 ALB','⚡ NLB','🗄️ CLB (Legacy)','🌍 Global Accelerator','☁️ CloudFront'],
    gcp:   ['🌐 Ext. HTTP(S) LB','🏢 Int. HTTP(S) LB','⚡ Ext. TCP/UDP','🏠 Int. TCP/UDP','🚀 Cloud CDN','🔄 Traffic Director'],
  },
};

// ── SVG DIAGRAM HELPERS ──
function B(x,y,w,h,lb,sb,col,rx=9){const F={blue:'#ebf4fc',teal:'#e0f7fa',green:'#e8f5e8',amber:'#fff8ed',red:'#fce8e9',gray:'#f3f7fb',purple:'#f3e8fd'};const S={blue:'#0078d4',teal:'#00b4d8',green:'#107c10',amber:'#e07000',red:'#a4262c',gray:'#a0b8cc',purple:'#7b2fbe'};const TX={blue:'#004578',teal:'#006478',green:'#0a5007',amber:'#5a3000',red:'#6b0c0e',gray:'#3a5068',purple:'#4a1580'};const f=F[col]||F.blue,s=S[col]||S.blue,t=TX[col]||TX.blue;const cy=sb?y+h/2-7:y+h/2;return`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${f}" stroke="${s}" stroke-width="1.5"/><text x="${x+w/2}" y="${cy}" text-anchor="middle" dominant-baseline="central" font-family="'DM Sans',sans-serif" font-size="14" font-weight="600" fill="${t}">${lb}</text>${sb?`<text x="${x+w/2}" y="${y+h/2+11}" text-anchor="middle" dominant-baseline="central" font-family="'DM Sans',sans-serif" font-size="12" fill="${t}" opacity=".8">${sb}</text>`:''}`;}
function A(x1,y1,x2,y2,col='#0078d4'){const id='m'+Math.abs(x1+y1+x2+y2);return`<defs><marker id="${id}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M2 1L8 5L2 9" fill="none" stroke="${col}" stroke-width="2" stroke-linecap="round"/></marker></defs><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${col}" stroke-width="2" class="fa" marker-end="url(#${id})"/>`;}
function N(x,y,t){return`<text x="${x}" y="${y}" font-family="'DM Sans',sans-serif" font-size="13" fill="#6a8ba4">${t}</text>`;}
function SVG(c,h=268){return`<svg viewBox="0 0 780 ${h}" xmlns="http://www.w3.org/2000/svg">${c}</svg>`;}

// ── GLOSSY ICON BUILDER ──
function gi(iid,bg1,bg2,shape){return`<svg width="80" height="80" viewBox="0 0 72 72" xmlns="http://www.w3.org/2000/svg" style="filter:drop-shadow(0 6px 18px ${bg1}70)"><defs><radialGradient id="gb_${iid}" cx="35%" cy="28%" r="72%"><stop offset="0%" stop-color="${bg2}"/><stop offset="100%" stop-color="${bg1}"/></radialGradient><radialGradient id="gs_${iid}" cx="42%" cy="18%" r="62%"><stop offset="0%" stop-color="rgba(255,255,255,0.62)"/><stop offset="100%" stop-color="rgba(255,255,255,0)"/></radialGradient></defs><rect x="4" y="5" width="64" height="63" rx="16" fill="url(#gb_${iid})"/><rect x="4" y="5" width="64" height="35" rx="16" fill="url(#gs_${iid})" opacity="0.75"/><rect x="4" y="28" width="64" height="12" fill="url(#gs_${iid})" opacity="0.22"/>${shape}<rect x="4" y="5" width="64" height="63" rx="16" fill="none" stroke="rgba(255,255,255,0.28)" stroke-width="1.5"/></svg>`;}

const ICONS = {
'azure_lb':gi('alb','#004578','#1e90d0','<g transform="translate(36,39)" fill="white"><rect x="-18" y="-2.5" width="36" height="5" rx="2.5"/><rect x="-1.5" y="-17" width="3" height="19" rx="1.5"/><circle cx="-12" cy="-13" r="3.5" fill="none" stroke="white" stroke-width="2.5"/><circle cx="12" cy="-13" r="3.5" fill="none" stroke="white" stroke-width="2.5"/><line x1="-12" y1="-9.5" x2="-1.5" y2="-2.5" stroke="white" stroke-width="1.8" opacity=".7"/><line x1="12" y1="-9.5" x2="1.5" y2="-2.5" stroke="white" stroke-width="1.8" opacity=".7"/><rect x="-2.5" y="3" width="5" height="9" rx="2" opacity=".6"/></g>'),
'azure_appgw':gi('agw','#003a70','#0e7ad4','<g transform="translate(36,37)" fill="none"><path d="M0-19 L14-12 L14 5 Q14 17 0 23 Q-14 17-14 5 L-14-12 Z" stroke="white" stroke-width="2.8" stroke-linejoin="round"/><path d="M-7 2 L-2 7 L8-5" stroke="white" stroke-width="3.2" stroke-linecap="round" stroke-linejoin="round"/></g>'),
'azure_afd':gi('afd','#004578','#0091da','<g transform="translate(36,37)"><circle cx="0" cy="0" r="16" fill="none" stroke="white" stroke-width="2.5"/><ellipse cx="0" cy="0" rx="8" ry="16" fill="none" stroke="white" stroke-width="1.8" opacity=".65"/><line x1="-16" y1="0" x2="16" y2="0" stroke="white" stroke-width="1.6" opacity=".6"/><line x1="-13" y1="-8" x2="13" y2="-8" stroke="white" stroke-width="1.4" opacity=".5"/><line x1="-13" y1="8" x2="13" y2="8" stroke="white" stroke-width="1.4" opacity=".5"/><path d="M7-18 L14-18 L14-11" stroke="white" stroke-width="2.8" fill="none" stroke-linecap="round"/><line x1="14" y1="-18" x2="3" y2="-7" stroke="white" stroke-width="2.8" stroke-linecap="round"/></g>'),
'azure_tm':gi('atm','#003060','#0078d4','<g transform="translate(36,36)" fill="white"><circle cx="0" cy="-14" r="5.5"/><circle cx="-14" cy="12" r="4.5"/><circle cx="14" cy="12" r="4.5"/><line x1="0" y1="-8.5" x2="-12" y2="8" stroke="white" stroke-width="2.5" opacity=".8"/><line x1="0" y1="-8.5" x2="12" y2="8" stroke="white" stroke-width="2.5" opacity=".8"/><line x1="-9" y1="3" x2="9" y2="3" stroke="white" stroke-width="1.8" opacity=".45"/></g>'),
'azure_apim':gi('api','#3b0070','#7b2fbe','<g transform="translate(36,36)" fill="white"><rect x="-7" y="-19" width="14" height="20" rx="3"/><rect x="-3.5" y="-24" width="3.5" height="7" rx="1.8"/><rect x="0" y="-24" width="3.5" height="7" rx="1.8"/><path d="M-7 1 L-7 11 Q-7 19 0 19 Q7 19 7 11 L7 1Z" opacity=".7"/><circle cx="0" cy="8" r="3.5" fill="rgba(255,255,255,.35)"/></g>'),
'azure_afd_appgw':gi('aag','#002855','#0a60aa','<g transform="translate(36,36)"><circle cx="0" cy="-8" r="13" fill="none" stroke="white" stroke-width="2.5"/><ellipse cx="0" cy="-8" rx="6.5" ry="13" fill="none" stroke="white" stroke-width="1.5" opacity=".55"/><line x1="-13" y1="-8" x2="13" y2="-8" stroke="white" stroke-width="1.4" opacity=".5"/><path d="M-9 9 L0 3 L9 9 L9 19 Q9 26 0 28 Q-9 26-9 19Z" fill="white" opacity=".88"/><path d="M-4 16 L-1 19 L6 12" stroke="rgba(0,40,100,.7)" stroke-width="2.5" fill="none" stroke-linecap="round" stroke-linejoin="round"/></g>'),
'azure_afd_lb':gi('aal','#002855','#0a72c8','<g transform="translate(36,36)"><circle cx="0" cy="-12" r="12" fill="none" stroke="white" stroke-width="2.5"/><ellipse cx="0" cy="-12" rx="6" ry="12" fill="none" stroke="white" stroke-width="1.5" opacity=".55"/><rect x="-13" y="6" width="26" height="5" rx="2.5" fill="white" opacity=".9"/><rect x="-9" y="14" width="5" height="8" rx="2" fill="white" opacity=".65"/><rect x="-1.5" y="14" width="5" height="8" rx="2" fill="white" opacity=".65"/><rect x="4" y="14" width="5" height="8" rx="2" fill="white" opacity=".65"/></g>'),
'aws_alb':gi('awa','#7a4200','#e07000','<g transform="translate(36,36)" fill="white"><rect x="-15" y="-6" width="12" height="12" rx="3.5"/><path d="M-3 0 L9-12 M-3 0 L11 0 M-3 0 L9 12" stroke="white" stroke-width="2.8" fill="none" stroke-linecap="round"/><circle cx="15" cy="-12" r="4.5"/><circle cx="15" cy="0" r="4.5"/><circle cx="15" cy="12" r="4.5"/></g>'),
'aws_nlb':gi('awn','#7a3800','#d47000','<g transform="translate(36,36)" fill="white"><path d="M5-21 L-7 2 L2 2 L-5 21 L16-5 L7-5 L18-21Z"/></g>'),
'aws_clb':gi('awc','#5a0000','#a42020','<g transform="translate(36,36)" fill="white"><rect x="-15" y="-17" width="30" height="21" rx="3.5" opacity=".9"/><rect x="-15" y="7" width="30" height="11" rx="3" opacity=".65"/><rect x="-10" y="-13" width="20" height="3.5" rx="1.8" fill="rgba(180,20,20,.55)"/><rect x="-10" y="-7" width="13" height="3.5" rx="1.8" fill="rgba(180,20,20,.55)"/></g>'),
'aws_ga':gi('awg','#7a4200','#d08000','<g transform="translate(36,37)"><circle cx="0" cy="0" r="16" fill="none" stroke="white" stroke-width="2.5"/><ellipse cx="0" cy="0" rx="8" ry="16" fill="none" stroke="white" stroke-width="1.6" opacity=".55"/><line x1="-16" y1="0" x2="16" y2="0" stroke="white" stroke-width="1.5" opacity=".5"/><path d="M2-11 L-3 2 L2 2 L-2 11 L9 0 L4 0 L9-11Z" fill="white"/></g>'),
'aws_cf':gi('awf','#7a4200','#e07000','<g transform="translate(36,35)" fill="white"><path d="M-10 3 Q-18 3-18-7 Q-18-19-6-19 Q-4-26 6-26 Q19-26 21-15 Q28-14 28-5 Q28 5 18 5 L-10 5Z" transform="scale(0.78)"/><path d="M-8 9 L-15 20 M0 9 L0 21 M8 9 L15 20" stroke="white" stroke-width="2.5" fill="none" stroke-linecap="round" opacity=".55"/></g>'),
'gcp_ext_https':gi('geh','#0d3b8c','#2878e8','<g transform="translate(36,37)"><circle cx="0" cy="0" r="16" fill="none" stroke="white" stroke-width="2.5"/><ellipse cx="0" cy="0" rx="7.5" ry="16" fill="none" stroke="white" stroke-width="1.6" opacity=".6"/><line x1="-16" y1="-5" x2="16" y2="-5" stroke="white" stroke-width="1.5" opacity=".55"/><line x1="-16" y1="5" x2="16" y2="5" stroke="white" stroke-width="1.4" opacity=".45"/><path d="M-7 2 L-2 7 L8-5" stroke="white" stroke-width="3.2" fill="none" stroke-linecap="round" stroke-linejoin="round"/></g>'),
'gcp_int_https':gi('gih','#0d3b8c','#1565c0','<g transform="translate(36,36)" fill="white"><rect x="-15" y="-15" width="30" height="30" rx="6" fill="none" stroke="white" stroke-width="2.5"/><rect x="-9" y="-9" width="8" height="11" rx="2.5" opacity=".92"/><rect x="1" y="-9" width="8" height="11" rx="2.5" opacity=".92"/><rect x="-5.5" y="5" width="11" height="9" rx="2" opacity=".72"/></g>'),
'gcp_ext_tcp':gi('get','#0d3b8c','#1a80e8','<g transform="translate(36,36)" fill="white"><path d="M5-21 L-7 2 L2 2 L-5 21 L16-5 L7-5 L18-21Z"/></g>'),
'gcp_int_tcp':gi('git2','#083080','#1060c0','<g transform="translate(36,36)" fill="white"><path d="M0-19 L17 1 L13 1 L13 18 L-13 18 L-13 1 L-17 1Z" opacity=".9"/><rect x="-5.5" y="5" width="11" height="13" rx="2.5" fill="rgba(0,40,120,.35)"/></g>'),
'gcp_cdn':gi('gcdn','#0d3b8c','#1a73e8','<g transform="translate(36,34)" fill="white"><path d="M-8 2 Q-16 2-16-8 Q-16-19-5-19 Q-3-26 6-26 Q18-26 20-15 Q27-14 27-5 Q27 5 17 5 L-8 5Z" transform="scale(0.78) translate(0,2)"/><path d="M-13 13 L-9 22 M0 13 L0 23 M13 13 L9 22" stroke="white" stroke-width="2.6" fill="none" stroke-linecap="round"/></g>'),
'gcp_td':gi('gtd','#0d3b8c','#1a73e8','<g transform="translate(36,36)" fill="white"><circle cx="0" cy="0" r="5.5"/><circle cx="0" cy="-16" r="4.5"/><circle cx="-15" cy="10" r="4.5"/><circle cx="15" cy="10" r="4.5"/><line x1="0" y1="-11.5" x2="0" y2="-5.5" stroke="white" stroke-width="2.2"/><line x1="-12" y1="7.5" x2="-4.5" y2="3.2" stroke="white" stroke-width="2.2"/><line x1="12" y1="7.5" x2="4.5" y2="3.2" stroke="white" stroke-width="2.2"/><line x1="-11" y1="9" x2="11" y2="9" stroke="white" stroke-width="1.5" opacity=".38"/></g>'),
};

// ── DIAGRAMS ──
const DIAG = {
azure_lb:()=>SVG(`${B(20,108,125,46,'Internet / VNet','Public or private','gray')}${A(145,131,218,131,'#0078d4')}${B(218,88,172,88,'Azure Load Balancer','Layer 4 · Regional','blue')}${A(390,108,460,90,'#107c10')}${A(390,131,460,131,'#107c10')}${A(390,154,460,170,'#107c10')}${B(460,70,140,46,'VM Backend 1','','green')}${B(460,110,140,46,'VM Backend 2','','green')}${B(460,150,140,46,'VM Backend 3','','green')}${N(20,252,'Passthrough · Millions req/s · Ultra-low latency · Zone-redundant')}`),
azure_appgw:()=>SVG(`${B(20,108,110,46,'Internet','Public','gray')}${A(130,131,205,131,'#0078d4')}${B(205,84,172,94,'Application Gateway','Layer 7 · WAF · SSL','blue')}${A(377,106,450,84,'#0078d4')}${A(377,131,450,131,'#0078d4')}${A(377,155,450,173,'#0078d4')}${B(450,64,145,46,'API Backend','','green')}${B(450,107,145,46,'Web Backend','','green')}${B(450,151,145,46,'Media Backend','','teal')}${N(20,252,'Terminating proxy · TLS offload · Path routing · WAF · Session affinity')}`),
azure_afd:()=>SVG(`${B(20,65,88,36,'Users','Americas','gray',7)}${B(20,114,88,36,'Users','Asia','gray',7)}${B(20,163,88,36,'Users','Europe','gray',7)}${A(108,83,185,108,'#0078d4')}${A(108,132,185,130,'#0078d4')}${A(108,181,185,155,'#0078d4')}${B(185,92,152,76,'Azure Front Door','Global Anycast CDN','blue')}${A(337,108,412,85,'#00b4d8')}${A(337,142,412,143,'#00b4d8')}${A(337,160,412,205,'#00b4d8')}${B(412,62,160,52,'Origin — East US','App Svc / AKS','green')}${B(412,127,160,52,'Origin — West EU','App Svc / AKS','green')}${B(412,196,160,52,'Origin — SE Asia','App Svc / AKS','teal')}${N(20,268,'Anycast → nearest PoP → Microsoft private WAN → origin')}`,285),
azure_tm:()=>SVG(`${B(20,110,110,46,'DNS Query','From client','gray')}${A(130,133,210,133,'#0078d4')}${B(210,100,168,66,'Traffic Manager','DNS-based routing','blue')}${A(378,118,452,92,'#0078d4')}${A(378,148,452,165,'#0078d4')}${B(452,70,162,50,'Endpoint Region A','App Gw / App Svc','green')}${B(452,147,162,50,'Endpoint Region B','App Gw / App Svc','amber')}${N(20,242,'DNS-only · No data plane · Failover limited by DNS TTL · Any protocol')}`,258),
azure_apim:()=>SVG(`${B(20,108,110,46,'API Clients','Web/Mobile/B2B','gray')}${A(130,131,210,131,'#0078d4')}${B(210,88,162,86,'API Management','Gateway · Auth · Rate limit','blue')}${A(372,106,448,84,'#0078d4')}${A(372,131,448,131,'#0078d4')}${A(372,155,448,170,'#0078d4')}${B(448,62,158,48,'API Backend 1','Function / App Svc','green')}${B(448,108,158,48,'API Backend 2','Function / App Svc','green')}${B(448,154,158,48,'API Backend 3','Function / App Svc','teal')}${N(20,248,'API gateway first · Auth offload · Rate limiting')}`),
azure_afd_appgw:()=>SVG(`${B(20,116,88,46,'Internet','Global','gray',7)}${A(108,139,180,139,'#0078d4')}${B(180,108,145,68,'Front Door','Global WAF · CDN','blue')}${A(325,127,396,98,'#00b4d8')}${A(325,147,396,168,'#00b4d8')}${B(396,70,148,56,'App Gateway','Region A · WAF','purple')}${B(396,148,148,56,'App Gateway','Region B · WAF','purple')}${A(544,88,617,76,'#107c10')}${A(544,107,617,107,'#107c10')}${A(544,160,617,153,'#107c10')}${A(544,178,617,182,'#107c10')}${B(617,56,128,38,'Backends A','VM/AKS','green')}${B(617,96,128,38,'Backends B','VM/AKS','green')}${B(617,140,128,38,'Backends C','VM/AKS','teal')}${B(617,180,128,38,'Backends D','VM/AKS','teal')}${N(20,252,'AFD (global WAF+CDN) → App Gateway per region → backends')}`,268),
azure_afd_lb:()=>SVG(`${B(20,116,88,46,'Internet','Global','gray',7)}${A(108,139,180,139,'#0078d4')}${B(180,108,145,68,'Front Door','Global CDN · WAF','blue')}${A(325,120,396,94,'#00b4d8')}${A(325,155,396,167,'#00b4d8')}${B(396,68,142,53,'Load Balancer','Region A · L4','purple')}${B(396,147,142,53,'Load Balancer','Region B · L4','purple')}${A(538,86,612,74,'#107c10')}${A(538,103,612,106,'#107c10')}${A(538,162,612,155,'#107c10')}${A(538,176,612,183,'#107c10')}${B(612,54,138,40,'VM Pool A','VMSS','green')}${B(612,96,138,40,'VM Pool A2','VMSS','green')}${B(612,142,138,40,'VM Pool B','VMSS','teal')}${B(612,182,138,40,'VM Pool B2','VMSS','teal')}${N(20,252,'AFD (global HTTP) → Regional Load Balancer → VM/VMSS')}`,268),
aws_alb:()=>SVG(`${B(20,108,110,46,'Internet','Public / Internal','gray')}${A(130,131,208,131,'#e07000')}${B(208,85,175,93,'ALB','App Load Balancer · L7','amber')}${A(383,108,455,86,'#e07000')}${A(383,131,455,131,'#e07000')}${A(383,154,455,172,'#e07000')}${B(455,64,146,46,'Target Group 1','EC2 / ECS / Lambda','green')}${B(455,107,146,46,'Target Group 2','EC2 / ECS / IP','green')}${B(455,150,146,46,'Target Group 3','EC2 / ECS','teal')}${N(20,252,'Listener rules · Host/path routing · WAF attach · gRPC · WebSockets')}`),
aws_nlb:()=>SVG(`${B(20,110,115,46,'Internet','or Internal','gray')}${A(135,133,213,133,'#e07000')}${B(213,90,170,88,'NLB','Network LB · Layer 4','amber')}${A(383,110,455,90,'#e07000')}${A(383,133,455,133,'#e07000')}${A(383,156,455,172,'#e07000')}${B(455,68,146,46,'Target Group 1','EC2 / IP / Lambda','green')}${B(455,108,146,46,'Target Group 2','EC2 / IP','green')}${B(455,148,146,46,'Target Group 3','EC2 / ECS','green')}${N(20,252,'Static Elastic IP · TLS passthrough or termination · PrivateLink')}`),
aws_clb:()=>SVG(`${B(20,108,115,46,'Internet','Legacy','gray')}${A(135,131,213,131,'#a4262c')}${B(213,90,170,82,'CLB','Classic LB · Legacy','red')}${A(383,110,455,90,'#a4262c')}${A(383,131,455,131,'#a4262c')}${A(383,153,455,170,'#a4262c')}${B(455,68,146,46,'EC2 Instance 1','','gray')}${B(455,107,146,46,'EC2 Instance 2','','gray')}${B(455,146,146,46,'EC2 Instance 3','','gray')}${N(20,252,'⚠ Legacy — use ALB or NLB for all new workloads')}`),
aws_ga:()=>SVG(`${B(20,65,86,36,'Users','Americas','gray',7)}${B(20,113,86,36,'Users','Asia','gray',7)}${B(20,161,86,36,'Users','Europe','gray',7)}${A(106,83,183,110,'#e07000')}${A(106,131,183,131,'#e07000')}${A(106,179,183,155,'#e07000')}${B(183,96,152,70,'Global Accelerator','Anycast · AWS backbone','amber')}${A(335,110,412,87,'#107c10')}${A(335,141,412,144,'#107c10')}${A(335,160,412,198,'#107c10')}${B(412,64,158,50,'us-east — ALB/NLB','','green')}${B(412,127,158,50,'eu-west — ALB/NLB','','green')}${B(412,193,158,50,'ap-south — ALB/NLB','','teal')}${N(20,265,'2 static anycast IPs · AWS private network · TCP+UDP+HTTP · ~30s failover')}`,280),
aws_cf:()=>SVG(`${B(20,65,86,36,'Users','Global','gray',7)}${B(20,113,86,36,'Users','Asia','gray',7)}${B(20,161,86,36,'Users','Europe','gray',7)}${A(106,83,183,110,'#e07000')}${A(106,131,183,131,'#e07000')}${A(106,179,183,155,'#e07000')}${B(183,96,152,70,'CloudFront','Global CDN · 550+ PoPs','amber')}${A(335,110,412,87,'#107c10')}${A(335,141,412,144,'#107c10')}${A(335,161,412,200,'#107c10')}${B(412,64,158,48,'S3 / ALB / API GW','Origin 1','green')}${B(412,127,158,48,'S3 / ALB custom','Origin 2','green')}${B(412,193,158,48,'MediaPackage','Origin 3','teal')}${N(20,265,'550+ PoPs · Lambda@Edge · Origin groups for HA · WAF attach')}`,280),
gcp_ext_https:()=>SVG(`${B(20,108,110,46,'Internet','Public','gray')}${A(130,131,208,131,'#1a73e8')}${B(208,85,173,93,'Ext. HTTP(S) LB','Global or Regional · L7','blue')}${A(381,108,453,86,'#1a73e8')}${A(381,131,453,131,'#1a73e8')}${A(381,154,453,170,'#1a73e8')}${B(453,64,146,46,'Backend Svc 1','GCE / GKE / NEG','green')}${B(453,107,146,46,'Backend Svc 2','GCE / GKE','green')}${B(453,150,146,46,'Backend Svc 3','Cloud Run / NEG','teal')}${N(20,252,'URL map routing · Cloud Armor WAF · Global anycast (Premium) · SSL certs')}`),
gcp_int_https:()=>SVG(`${B(20,108,115,46,'Internal','VPC clients','gray')}${A(135,131,212,131,'#1a73e8')}${B(212,85,173,93,'Int. HTTP(S) LB','Regional · L7 · VPC-internal','blue')}${A(385,108,455,86,'#1a73e8')}${A(385,131,455,131,'#1a73e8')}${A(385,154,455,170,'#1a73e8')}${B(455,64,146,46,'Backend Svc 1','GCE / GKE / NEG','green')}${B(455,107,146,46,'Backend Svc 2','GCE / GKE','green')}${B(455,150,146,46,'Backend Svc 3','Cloud Run','teal')}${N(20,252,'VPC-internal · Path routing · mTLS · Service Directory · Envoy-based')}`),
gcp_ext_tcp:()=>SVG(`${B(20,110,115,46,'Internet','Public','gray')}${A(135,133,213,133,'#1a73e8')}${B(213,90,170,86,'Ext. TCP/UDP LB','Regional · L4 · Passthrough','blue')}${A(383,110,455,90,'#1a73e8')}${A(383,133,455,133,'#1a73e8')}${A(383,155,455,172,'#1a73e8')}${B(455,68,148,46,'Backend 1','GCE instance group','green')}${B(455,108,148,46,'Backend 2','GCE instance group','green')}${B(455,148,148,46,'Backend 3','GCE instance group','teal')}${N(20,252,'Passthrough · Any TCP/UDP · Regional anycast · Preserves client source IP')}`),
gcp_int_tcp:()=>SVG(`${B(20,110,115,46,'Internal','VPC clients','gray')}${A(135,133,213,133,'#1a73e8')}${B(213,90,170,86,'Int. TCP/UDP LB','Regional · L4 · VPC-internal','blue')}${A(383,110,455,90,'#1a73e8')}${A(383,133,455,133,'#1a73e8')}${A(383,155,455,172,'#1a73e8')}${B(455,68,148,46,'Backend 1','GCE / GKE','green')}${B(455,108,148,46,'Backend 2','GCE / GKE','green')}${B(455,148,148,46,'Backend 3','GCE / GKE','teal')}${N(20,252,'VPC-internal · No public IP · GRE-based · All TCP/UDP ports')}`),
gcp_cdn:()=>SVG(`${B(20,65,86,36,'Users','Global','gray',7)}${B(20,113,86,36,'Users','Asia','gray',7)}${B(20,161,86,36,'Users','Europe','gray',7)}${A(106,83,183,110,'#1a73e8')}${A(106,131,183,131,'#1a73e8')}${A(106,179,183,155,'#1a73e8')}${B(183,96,152,70,'Cloud CDN','Google PoPs · Cache','blue')}${A(335,110,412,87,'#107c10')}${A(335,141,412,144,'#107c10')}${A(335,161,412,200,'#107c10')}${B(412,64,160,48,'GCS Bucket','Static origin','green')}${B(412,127,160,48,'Backend Service','GCE / GKE','green')}${B(412,193,160,48,'Cloud Run','Serverless','teal')}${N(20,265,'Must attach to External HTTP(S) LB · Cache-Control · Signed URLs')}`,280),
gcp_td:()=>SVG(`${B(20,120,110,46,'Microservice A','Envoy sidecar','gray')}${A(130,143,208,143,'#1a73e8')}${B(208,102,163,83,'Traffic Director','Service mesh · xDS API','blue')}${A(371,122,447,99,'#1a73e8')}${A(371,148,447,166,'#1a73e8')}${B(447,74,152,52,'Microservice B','Envoy sidecar','green')}${B(447,149,152,52,'Microservice C','Envoy sidecar','teal')}${N(20,252,'xDS API · Envoy sidecars · Traffic splitting · Circuit breaking · mTLS')}`),
};

// ── SERVICE CATALOGUE ──
const SVC = {
azure_lb:{cl:'azure',ic:'⚖️',nm:'Azure Load Balancer',tl:'Layer-4 · Regional · TCP/UDP · Ultra-low latency',tg:['Layer 4','Regional','TCP/UDP'],ds:'High-performance passthrough L4 LB. Handles millions of req/s, zone-redundant.',dk:'azure_lb',ft:['Zone-redundant HA','Outbound SNAT / NAT rules','Internal & external modes','HA Ports (all TCP/UDP)','Millions of req/sec','Standard + Basic SKUs','Passthrough — no proxy','Cross-region topology'],uw:['Database server backends','Game servers, MQTT, IoT','SMTP, FTP, custom protocols','VM/VMSS non-HTTP pools'],nf:'SSL offload, WAF, path routing — use Application Gateway.',nt:null,doc:'https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-overview'},
azure_appgw:{cl:'azure',ic:'🛡️',nm:'Application Gateway',tl:'Layer-7 · Regional · HTTP/HTTPS · WAF · SSL offload',tg:['Layer 7','Regional','WAF v2'],ds:'Regional L7 proxy with WAF, TLS termination, path routing, autoscaling.',dk:'azure_appgw',ft:['WAF v2 (OWASP rules)','TLS / SSL offload','URL path-based routing','URL rewriting & redirects','Cookie session affinity','Multi-site hosting (SNI)','Autoscaling Standard_v2','WebSockets & HTTP/2'],uw:['Single-region public web apps','API with WAF protection','AKS ingress (AGIC)','Multi-site/tenant hosting'],nf:'Non-HTTP TCP/UDP (use LB), global multi-region (add Front Door).',nt:null,doc:'https://learn.microsoft.com/en-us/azure/application-gateway/overview'},
azure_afd:{cl:'azure',ic:'🚀',nm:'Azure Front Door',tl:'Layer-7 · Global Anycast · CDN + WAF · Sub-second failover',tg:['Layer 7','Global','CDN + WAF'],ds:'Global anycast CDN and L7 LB via 100+ edge PoPs over Microsoft private WAN.',dk:'azure_afd',ft:['Anycast acceleration (100+ PoPs)','CDN edge caching','Global WAF (OWASP)','Sub-second failover','A/B & canary routing','Private Link origins','Path routing & URL rewrite','DDoS protection'],uw:['Global consumer web apps','E-commerce at scale','Multi-region active-active','Media & video delivery'],nf:'Non-HTTP TCP/UDP, single-region apps.',nt:null,doc:'https://learn.microsoft.com/en-us/azure/frontdoor/front-door-overview'},
azure_tm:{cl:'azure',ic:'🌐',nm:'Traffic Manager',tl:'DNS-based · Global · Any protocol · Priority / Weighted',tg:['DNS-based','Global','Any protocol'],ds:'DNS-level global LB. Directs clients via CNAME to nearest or healthiest endpoint.',dk:'azure_tm',ft:['DNS-based global routing','Priority, weighted, geographic','Any TCP/UDP protocol','Multi-region HA failover','Endpoint health monitoring','Nested profiles','Hybrid on-premises + Azure','No data-plane traffic'],uw:['Non-HTTP global routing','Multi-region DR','Geographic compliance','On-premises + Azure hybrid'],nf:'Sub-second failover (use AFD), HTTP inspection, WAF, SSL offload.',nt:null,doc:'https://learn.microsoft.com/en-us/azure/traffic-manager/traffic-manager-overview'},
azure_apim:{cl:'azure',ic:'🔌',nm:'API Management',tl:'Layer-7 · API gateway · Auth · Rate limiting',tg:['Layer 7','API gateway','JWT/OAuth2'],ds:'Managed API gateway with optional LB across backends.',dk:'azure_apim',ft:['JWT / OAuth2 validation','Rate limiting & throttling','Round-robin / weighted LB','Developer portal','Analytics & tracing','Response caching','Multi-backend federation','Versioning & subscriptions'],uw:['Multi-backend API federation','Global API gateway + auth','Monetised API products','B2B integration'],nf:'General web apps. Do not adopt APIM solely for load balancing.',nt:'⚠️ Only use APIM LB if already in architecture for API gateway purposes.',doc:'https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts'},
azure_afd_appgw:{cl:'azure',ic:'🚀',nm:'Front Door + App Gateway',tl:'Global WAF + Regional L7 + layered protection',tg:['Global + Regional','Dual WAF','IaaS / AKS'],ds:'AFD global edge WAF + CDN; App Gateway regional L7 routing + second WAF layer.',dk:'azure_afd_appgw',ft:['Global WAF at AFD edge','Regional WAF at App Gateway','Path routing per region','AKS ingress via AGIC','Private Link from AFD','Blue-green K8s deploys'],uw:['IaaS/AKS multi-region','Dual WAF compliance','Regulated industries','AKS + global distribution'],nf:'PaaS backends — use AFD + PaaS direct.',nt:'🔗 Internet → Front Door → App Gateway (per region) → VM/AKS',doc:'https://learn.microsoft.com/en-us/azure/frontdoor/front-door-faq'},
azure_afd_lb:{cl:'azure',ic:'🚀',nm:'Front Door + Load Balancer',tl:'Global HTTP + Regional VM load balancing',tg:['Global + Regional','HTTP + L4','IaaS VMs'],ds:'AFD handles global HTTP, CDN, WAF; regional LB distributes among VMs.',dk:'azure_afd_lb',ft:['Global anycast via AFD','Regional VM LB','WAF at global edge','Zone-redundant backends','Health probing at both layers'],uw:['IaaS web apps multi-region','VMSS behind global layer','Lift-and-shift + global reach'],nf:'Path routing within region — add App Gateway for that.',nt:'🔗 Internet → Front Door → Regional Load Balancer → VM/VMSS',doc:'https://learn.microsoft.com/en-us/azure/frontdoor/front-door-overview'},
aws_alb:{cl:'aws',ic:'🔀',nm:'ALB — Application Load Balancer',tl:'Layer-7 · Regional · HTTP/HTTPS · gRPC',tg:['Layer 7','Regional','HTTP/HTTPS/gRPC'],ds:'AWS L7 LB. Routes by host, path, header. Supports EC2, ECS, Lambda, IP targets.',dk:'aws_alb',ft:['Host & path-based routing','HTTP header / query routing','gRPC support','WebSockets','Lambda targets','Sticky sessions','WAF integration (AWS WAF)','Fixed response & redirects'],uw:['Web apps and APIs on AWS','Microservices path routing','ECS / Fargate workloads','Lambda targets'],nf:'TCP/UDP non-HTTP (use NLB), static IP requirement.',nt:null,doc:'https://docs.aws.amazon.com/elasticloadbalancing/latest/application/'},
aws_nlb:{cl:'aws',ic:'⚡',nm:'NLB — Network Load Balancer',tl:'Layer-4 · Regional · TCP/UDP/TLS · Static IP',tg:['Layer 4','Regional','TCP/UDP/TLS'],ds:'AWS L4 LB. Static Elastic IP per AZ. TLS passthrough or termination.',dk:'aws_nlb',ft:['Static Elastic IP per AZ','TLS passthrough or termination','Ultra-low latency','UDP support','PrivateLink endpoint support','Cross-zone load balancing','Preserve source IP'],uw:['Non-HTTP TCP/UDP workloads','Static IP requirement','PrivateLink services','Gaming, IoT, financial'],nf:'HTTP routing rules, WAF, path-based routing — use ALB.',nt:null,doc:'https://docs.aws.amazon.com/elasticloadbalancing/latest/network/'},
aws_clb:{cl:'aws',ic:'🗄️',nm:'CLB — Classic Load Balancer',tl:'Legacy · Layer-4 & 7 · Not for new workloads',tg:['Legacy','Layer 4+7','EC2-Classic'],ds:'Original AWS LB. AWS recommends migrating to ALB or NLB.',dk:'aws_clb',ft:['Basic HTTP/HTTPS routing','TCP/SSL passthrough','Sticky sessions (cookies)','EC2-Classic support'],uw:['Existing legacy workloads only'],nf:'All new workloads — use ALB for HTTP/S or NLB for TCP/UDP.',nt:'⚠️ Legacy — AWS recommends migrating all CLBs to ALB or NLB.',doc:'https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/'},
aws_ga:{cl:'aws',ic:'🌍',nm:'AWS Global Accelerator',tl:'Global Anycast · TCP + UDP + HTTP · AWS backbone',tg:['Global','Anycast','TCP/UDP/HTTP'],ds:'Global anycast service routing over AWS backbone. 2 static anycast IPs.',dk:'aws_ga',ft:['2 static anycast IPs','AWS global private network','TCP + UDP + HTTP support','~30 second failover','Traffic dials per endpoint','Works with ALB, NLB, EC2'],uw:['Global TCP/UDP applications','Gaming, IoT, VoIP globally','Static IP globally','Non-HTTP global routing'],nf:'CDN / caching (use CloudFront).',nt:null,doc:'https://docs.aws.amazon.com/global-accelerator/'},
aws_cf:{cl:'aws',ic:'☁️',nm:'Amazon CloudFront',tl:'Global CDN · 550+ PoPs · HTTP/S · Lambda@Edge',tg:['Global CDN','Layer 7','HTTP/S only'],ds:'AWS global CDN with 550+ PoPs. Caches at edge, Lambda@Edge and WAF integration.',dk:'aws_cf',ft:['550+ edge PoPs globally','Edge caching & compression','Lambda@Edge / CF Functions','Origin groups for HA failover','HTTPS with SNI & custom certs','WAF integration (AWS WAF)','Signed URLs & cookies'],uw:['Global web app acceleration','Static asset delivery (S3)','Media streaming','API caching at edge'],nf:'Non-HTTP TCP/UDP — use Global Accelerator.',nt:null,doc:'https://docs.aws.amazon.com/cloudfront/'},
gcp_ext_https:{cl:'gcp',ic:'🌐',nm:'External HTTP(S) Load Balancer',tl:'Layer-7 · Global (Premium) or Regional · Anycast',tg:['Layer 7','Global / Regional','HTTP/HTTPS'],ds:'GCPs primary HTTP/S LB. Global mode uses anycast and Google premium network.',dk:'gcp_ext_https',ft:['URL map routing (host + path)','Cloud Armor WAF','Global anycast (Premium tier)','SSL certs (managed)','HTTP/2 & gRPC','GCE, GKE, Cloud Run, NEG','Identity-Aware Proxy (IAP)'],uw:['Public web apps on GCP','Microservices path routing','GKE Ingress','Global multi-region failover'],nf:'TCP/UDP non-HTTP (use TCP/UDP LB), internal apps (use Internal HTTP(S) LB).',nt:null,doc:'https://cloud.google.com/load-balancing/docs/https'},
gcp_int_https:{cl:'gcp',ic:'🏢',nm:'Internal HTTP(S) Load Balancer',tl:'Layer-7 · Regional · VPC-internal · Envoy proxy',tg:['Layer 7','Regional','VPC internal'],ds:'Envoy-based internal L7 LB for VPC traffic. Supports path routing, mTLS.',dk:'gcp_int_https',ft:['VPC-internal only','Path-based routing','mTLS support','Service Directory integration','Envoy proxy-based','gRPC support'],uw:['Internal microservices routing','Internal GKE services','mTLS between services'],nf:'Public internet (use External HTTP(S) LB).',nt:null,doc:'https://cloud.google.com/load-balancing/docs/l7-internal'},
gcp_ext_tcp:{cl:'gcp',ic:'⚡',nm:'External TCP/UDP Load Balancer',tl:'Layer-4 · Regional · Passthrough · Any protocol',tg:['Layer 4','Regional','TCP/UDP'],ds:'Regional passthrough L4 LB for external TCP/UDP traffic.',dk:'gcp_ext_tcp',ft:['Regional anycast','Preserves client source IP','All TCP/UDP ports','Hash-based session affinity','Passthrough — no SSL offload'],uw:['Non-HTTP external workloads','Gaming servers, IoT','TLS passthrough to backend'],nf:'HTTP/S routing (use External HTTP(S) LB).',nt:null,doc:'https://cloud.google.com/load-balancing/docs/network'},
gcp_int_tcp:{cl:'gcp',ic:'🏠',nm:'Internal TCP/UDP Load Balancer',tl:'Layer-4 · Regional · VPC-internal · GRE-based',tg:['Layer 4','Regional','VPC internal'],ds:'GRE-based internal L4 LB for VPC TCP/UDP traffic.',dk:'gcp_int_tcp',ft:['VPC-internal only','All TCP/UDP ports','GRE encapsulation','Flow symmetry preserved','No public IP exposure'],uw:['Internal TCP/UDP workloads','Database clusters','NVA / firewall HA'],nf:'Public internet (use External TCP/UDP LB).',nt:null,doc:'https://cloud.google.com/load-balancing/docs/internal'},
gcp_cdn:{cl:'gcp',ic:'🚀',nm:'Cloud CDN + HTTP(S) LB',tl:'Global CDN · Google PoPs · Attached to HTTP(S) LB',tg:['Global CDN','Layer 7','HTTP/HTTPS'],ds:'Cloud CDN attaches to External HTTP(S) LB. Caches at Google PoPs globally.',dk:'gcp_cdn',ft:['Google global PoPs','Cache-Control header support','Signed URLs & cookies','Cache invalidation API','Origin shield','Negative caching'],uw:['Static asset delivery','Video on demand','Web app acceleration'],nf:'TCP/UDP traffic. Must be used with External HTTP(S) LB.',nt:'💡 Cloud CDN attaches to External HTTP(S) LB as a feature — not standalone.',doc:'https://cloud.google.com/cdn/docs'},
gcp_td:{cl:'gcp',ic:'🔄',nm:'Traffic Director',tl:'Service mesh · xDS · Envoy sidecars · Internal L7',tg:['Service mesh','xDS API','GKE + GCE'],ds:'Managed service mesh control plane. Distributes xDS config to Envoy sidecars.',dk:'gcp_td',ft:['xDS API (Envoy native)','Traffic splitting & canary','Circuit breaking','mTLS between services','GKE & GCE support','Proxyless gRPC'],uw:['Microservices on GKE/GCE','Service mesh without Istio overhead','Proxyless gRPC services'],nf:'External/public traffic.',nt:'💡 Traffic Director is the control plane — Envoy sidecars stay as data plane.',doc:'https://cloud.google.com/traffic-director/docs'},
};

// ── DECISION TREES ──
const TREE = {
azure:{
  root:{id:'q1',ey:'Step 1 of 4',q:'What type of traffic does your application handle?',h:'Layer-7 LBs understand HTTP (headers, paths, cookies). Layer-4 routes raw TCP/UDP — faster but traffic-agnostic.',two:false,opts:[{ic:'🌐',lb:'Web app (HTTP/HTTPS)',ds:'Websites, REST APIs — anything HTTP-driven',cr:'HTTP/HTTPS',nx:'q2'},{ic:'🔌',lb:'Non-HTTP (TCP / UDP)',ds:'Databases, game servers, IoT, SMTP, FTP',cr:'TCP/UDP',nx:'R_lb'}]},
  nodes:{q2:{id:'q2',ey:'Step 2 of 4',q:'Is your app internet-facing?',h:'Public apps need a frontend IP reachable from the internet. Internal apps stay within your Azure VNet.',two:true,opts:[{ic:'🌍',lb:'Yes — public internet',ds:'Accessible from anywhere',cr:'Internet-facing',nx:'q3'},{ic:'🏢',lb:'No — internal only',ds:'Private, within VNet',cr:'Internal',nx:'R_lb'}]},q3:{id:'q3',ey:'Step 3 of 4',q:'Deployed across multiple Azure regions?',h:'Global LBs route across regions. Regional LBs distribute within one region only.',two:true,opts:[{ic:'🗺️',lb:'Yes — multi-region',ds:'Deployed in 2+ Azure regions',cr:'Multi-region',nx:'q4'},{ic:'📍',lb:'No — single region',ds:'All backends in one region',cr:'Single region',nx:'R_appgw'}]},q4:{id:'q4',ey:'Step 4 of 4',q:'What does your global layer need to do?',h:'Front Door = anycast CDN + WAF + sub-second failover. Traffic Manager = DNS routing only.',two:false,opts:[{ic:'⚡',lb:'Performance acceleration + CDN',ds:'Anycast, edge caching, global WAF, sub-second failover',cr:'CDN + Acceleration',nx:'R_afd'},{ic:'🔒',lb:'SSL offload or L7 processing',ds:'TLS termination, path routing — no CDN needed',cr:'SSL + L7',nx:'q5'},{ic:'🌐',lb:'DNS-based global routing only',ds:'Route via DNS to nearest region',cr:'DNS routing',nx:'R_tm'}]},q5:{id:'q5',ey:'Step 4b',q:'What is your backend hosting type?',h:'The right combination depends on how your workload is hosted.',two:false,opts:[{ic:'☁️',lb:'PaaS (App Service, Functions)',ds:'Managed Azure services',cr:'PaaS',nx:'R_afd_paas'},{ic:'🖥️',lb:'IaaS (VMs / VMSS)',ds:'You manage your own VMs',cr:'IaaS/VMs',nx:'R_afd_lb'},{ic:'🐳',lb:'AKS (Kubernetes)',ds:'Containerised workloads on AKS',cr:'AKS',nx:'R_afd_appgw'},{ic:'🔌',lb:'API-only (API Management)',ds:'HTTP APIs fronted by APIM',cr:'API Mgmt',nx:'R_apim'}]}},
  results:{R_lb:{k:'azure_lb',w:'Your traffic is non-HTTP (TCP/UDP). Azure Load Balancer operates at Layer 4, handles millions of req/s with ultra-low latency, and is zone-redundant.'},R_appgw:{k:'azure_appgw',w:'Single-region, internet-facing web app. Application Gateway is a regional L7 proxy that terminates TLS, inspects HTTP headers/paths, applies WAF rules.'},R_afd:{k:'azure_afd',w:'Multi-region + performance acceleration. Azure Front Door routes via 100+ anycast edge PoPs over Microsoft private WAN — with built-in WAF and sub-second failover.'},R_tm:{k:'azure_tm',w:'Global DNS-level routing without HTTP inspection. Traffic Manager uses DNS to direct clients to the nearest or healthiest endpoint. Works with any protocol.'},R_afd_paas:{k:'azure_afd',w:'For PaaS backends across regions, Azure Front Door routes directly to App Service or Functions via Private Link. No Application Gateway hop needed.'},R_afd_lb:{k:'azure_afd_lb',w:'For VM/VMSS backends across regions: Azure Front Door (global HTTP, CDN, WAF) combined with a regional Azure Load Balancer per region.'},R_afd_appgw:{k:'azure_afd_appgw',w:'For AKS or IaaS needing layered WAF: Front Door provides global edge WAF; Application Gateway provides regional L7 routing and second WAF layer.'},R_apim:{k:'azure_apim',w:'For API-only workloads: APIM handles authentication, rate limiting, and backend LB. Front Door provides global routing at the edge.'}},
},
aws:{
  root:{id:'q1',ey:'Step 1 of 4',q:'What type of traffic does your application handle?',h:'AWS has separate LBs for HTTP/S (ALB) and TCP/UDP (NLB). Choose based on your protocol.',two:false,opts:[{ic:'🌐',lb:'Web app (HTTP/HTTPS)',ds:'Web apps, REST APIs, gRPC — anything HTTP-based',cr:'HTTP/HTTPS',nx:'q2'},{ic:'🔌',lb:'Non-HTTP (TCP / UDP)',ds:'Databases, gaming, IoT, FTP, custom protocols',cr:'TCP/UDP',nx:'R_nlb'}]},
  nodes:{q2:{id:'q2',ey:'Step 2 of 4',q:'Is your application internet-facing?',h:'Internet-facing ALBs get a public DNS name. Internal ALBs are accessible only within your VPC.',two:true,opts:[{ic:'🌍',lb:'Yes — public internet',ds:'Publicly accessible from the internet',cr:'Internet-facing',nx:'q3'},{ic:'🏢',lb:'No — internal VPC only',ds:'Only accessible within your VPC',cr:'Internal',nx:'R_alb'}]},q3:{id:'q3',ey:'Step 3 of 4',q:'Do you need global reach across multiple AWS regions?',h:'Global Accelerator and CloudFront both provide global reach — for different use cases.',two:true,opts:[{ic:'🗺️',lb:'Yes — global / multi-region',ds:'Users across the globe or 2+ regions',cr:'Multi-region',nx:'q4'},{ic:'📍',lb:'No — single region',ds:'All backends in one AWS region',cr:'Single region',nx:'R_alb'}]},q4:{id:'q4',ey:'Step 4 of 4',q:'What does your global layer need?',h:'CloudFront = CDN + HTTP caching. Global Accelerator = anycast static IPs with AWS backbone routing.',two:false,opts:[{ic:'⚡',lb:'CDN + edge caching + WAF',ds:'Cache HTTP content at 550+ PoPs, Lambda@Edge',cr:'CDN',nx:'R_cf'},{ic:'🌍',lb:'Anycast static IP + AWS backbone',ds:'Static IPs, non-HTTP, ~60% latency improvement',cr:'Anycast IP',nx:'R_ga'},{ic:'🔀',lb:'Just regional ALB with Route 53 failover',ds:'DNS-based failover between regional ALBs',cr:'DNS failover',nx:'R_alb'}]}},
  results:{R_nlb:{k:'aws_nlb',w:'Your traffic is non-HTTP. AWS Network Load Balancer operates at Layer 4, provides static Elastic IPs per AZ, and ultra-low latency.'},R_alb:{k:'aws_alb',w:'AWS Application Load Balancer provides L7 routing by host/path/header, WAF integration, and supports EC2, ECS, Lambda, and IP targets.'},R_cf:{k:'aws_cf',w:"You need a global CDN. Amazon CloudFront's 550+ PoPs cache content close to users, with WAF integration, Lambda@Edge, and origin groups for HA."},R_ga:{k:'aws_ga',w:'AWS Global Accelerator provides 2 static anycast IPs routed over the AWS backbone — ~60% faster. Supports TCP, UDP, and HTTP.'}},
},
gcp:{
  root:{id:'q1',ey:'Step 1 of 4',q:'What type of traffic does your application handle?',h:'GCP HTTP(S) LBs use URL maps. TCP/UDP LBs are passthrough. Traffic Director is for service mesh.',two:false,opts:[{ic:'🌐',lb:'Web app (HTTP/HTTPS)',ds:'Web apps, APIs, gRPC — anything HTTP-based',cr:'HTTP/HTTPS',nx:'q2'},{ic:'🔌',lb:'Non-HTTP (TCP / UDP)',ds:'Databases, gaming, IoT, custom TCP/UDP',cr:'TCP/UDP',nx:'q2tcp'},{ic:'🔄',lb:'Internal microservices / service mesh',ds:'Service-to-service routing, traffic splitting',cr:'Service mesh',nx:'R_td'}]},
  nodes:{q2:{id:'q2',ey:'Step 2 of 4',q:'Is your application internet-facing?',h:'External HTTP(S) LB serves public internet. Internal HTTP(S) LB is Envoy-based for VPC-internal routing.',two:true,opts:[{ic:'🌍',lb:'Yes — public internet',ds:'Publicly accessible from the internet',cr:'Internet-facing',nx:'q3'},{ic:'🏢',lb:'No — internal VPC only',ds:'Only accessible within your VPC',cr:'Internal',nx:'R_int_h'}]},q2tcp:{id:'q2tcp',ey:'Step 2 of 4',q:'Is your TCP/UDP app internet-facing?',h:'External TCP/UDP LB handles public TCP/UDP. Internal is VPC-private with GRE encapsulation.',two:true,opts:[{ic:'🌍',lb:'Yes — public internet',ds:'Publicly accessible TCP/UDP traffic',cr:'Internet-facing',nx:'R_ext_t'},{ic:'🏢',lb:'No — internal VPC only',ds:'Internal TCP/UDP within VPC only',cr:'Internal TCP',nx:'R_int_t'}]},q3:{id:'q3',ey:'Step 3 of 4',q:'Do you need global reach (Premium Tier)?',h:'GCP External HTTP(S) LB in Premium Tier is globally anycast. Standard Tier is regional.',two:true,opts:[{ic:'🗺️',lb:'Yes — global (Premium Tier)',ds:'Users across the globe, multi-region backends',cr:'Multi-region',nx:'q4'},{ic:'📍',lb:'No — single region (Standard Tier)',ds:'Regional backends, cost-optimised',cr:'Single region',nx:'R_ext_h_r'}]},q4:{id:'q4',ey:'Step 4 of 4',q:'Do you need edge caching (CDN)?',h:'Cloud CDN attaches to External HTTP(S) LB. It caches content at Google PoPs globally.',two:true,opts:[{ic:'⚡',lb:'Yes — cache at Google PoPs',ds:'Static assets, APIs, media — cache close to users',cr:'CDN',nx:'R_cdn'},{ic:'🌐',lb:'No — just global anycast routing',ds:'Global routing to backends without caching',cr:'No CDN',nx:'R_ext_h'}]}},
  results:{R_td:{k:'gcp_td',w:'Traffic Director is the managed service mesh control plane — xDS config to Envoy sidecars for traffic splitting, circuit breaking, and mTLS across GKE and GCE.'},R_int_h:{k:'gcp_int_https',w:'Internal HTTP(S) LB is Envoy-based regional L7 LB for VPC-internal traffic. Supports path routing, mTLS, and Service Directory.'},R_ext_t:{k:'gcp_ext_tcp',w:'External TCP/UDP LB is a regional passthrough L4 LB for public TCP/UDP. Preserves client source IP.'},R_int_t:{k:'gcp_int_tcp',w:'Internal TCP/UDP LB is GRE-based regional L4 LB for VPC-internal TCP/UDP. No public IP, preserves flow symmetry.'},R_ext_h_r:{k:'gcp_ext_https',w:'External HTTP(S) LB in Standard Tier provides regional L7 load balancing at lower cost. URL map routing to GCE, GKE, Cloud Run, and NEGs.'},R_ext_h:{k:'gcp_ext_https',w:"External HTTP(S) LB in Premium Tier uses Google's global anycast network to route via nearest PoP, then over Google's private backbone."},R_cdn:{k:'gcp_cdn',w:'Cloud CDN attaches to External HTTP(S) LB and caches content at Google PoPs. You get global anycast routing and edge caching in one solution.'}},
},
};

// ── COMPARE TABLES HTML ──
const COMPARE_HTML = `
<div style="margin-bottom:1.25rem"><h2 class="section-title">Cross-Cloud LB Comparison</h2><p class="section-sub">Equivalent load balancing services across Azure, AWS, and GCP.</p></div>
<div class="cmp-wrap"><div class="cmp-head"><h3>Layer 7 — HTTP/S Load Balancers</h3><p>Application-layer routing, SSL offload, WAF</p></div><div style="overflow-x:auto"><table class="ct"><thead><tr><th class="hd">Capability</th><th class="az">Azure</th><th class="aw">AWS</th><th class="gc">GCP</th></tr></thead><tbody>
<tr><td>Regional L7 LB</td><td>Application Gateway</td><td>ALB</td><td>External HTTP(S) LB (Regional)</td></tr>
<tr><td>Global L7 LB + CDN</td><td>Azure Front Door</td><td>CloudFront + ALB</td><td>Global HTTP(S) LB + Cloud CDN</td></tr>
<tr><td>WAF</td><td>WAF v2 (AppGW / AFD)</td><td>AWS WAF (ALB / CloudFront)</td><td>Cloud Armor</td></tr>
<tr><td>Path-based routing</td><td>App Gateway, Front Door</td><td>ALB listener rules</td><td>URL map in HTTP(S) LB</td></tr>
<tr><td>SSL offload</td><td>App Gateway, Front Door</td><td>ALB, CloudFront</td><td>External HTTP(S) LB</td></tr>
<tr><td>Internal L7 LB</td><td>App Gateway (private)</td><td>Internal ALB</td><td>Internal HTTP(S) LB</td></tr>
</tbody></table></div></div>
<div class="cmp-wrap" style="margin-top:1rem"><div class="cmp-head"><h3>Layer 4 — TCP/UDP Load Balancers</h3></div><div style="overflow-x:auto"><table class="ct"><thead><tr><th class="hd">Capability</th><th class="az">Azure</th><th class="aw">AWS</th><th class="gc">GCP</th></tr></thead><tbody>
<tr><td>Regional L4 (external)</td><td>Azure Load Balancer</td><td>NLB</td><td>External TCP/UDP LB</td></tr>
<tr><td>Regional L4 (internal)</td><td>Azure LB (internal)</td><td>Internal NLB</td><td>Internal TCP/UDP LB</td></tr>
<tr><td>Static IP</td><td>Standard SKU</td><td>Elastic IP (NLB)</td><td>External TCP/UDP LB</td></tr>
</tbody></table></div></div>
<div class="cmp-wrap" style="margin-top:1rem"><div class="cmp-head"><h3>Global Traffic Management</h3></div><div style="overflow-x:auto"><table class="ct"><thead><tr><th class="hd">Capability</th><th class="az">Azure</th><th class="aw">AWS</th><th class="gc">GCP</th></tr></thead><tbody>
<tr><td>Global anycast (HTTP)</td><td>Azure Front Door</td><td>CloudFront</td><td>Global External HTTP(S) LB</td></tr>
<tr><td>DNS-based global routing</td><td>Traffic Manager</td><td>Route 53</td><td>Cloud DNS</td></tr>
<tr><td>CDN</td><td>Front Door (built-in)</td><td>Amazon CloudFront</td><td>Cloud CDN (via HTTP(S) LB)</td></tr>
<tr><td>Service mesh</td><td>—</td><td>AWS App Mesh</td><td>Traffic Director</td></tr>
</tbody></table></div></div>`;

// ── PUBLIC API ──
return { META, ICONS, DIAG, SVC, TREE, COMPARE_HTML };
})();
